# Generated by Django 6.0.3 on 2026-03-29 08:11

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Business Name')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('mpesa_consumer_key', models.CharField(max_length=255, verbose_name='M-Pesa API Key')),
                ('mpesa_consumer_secret', models.CharField(max_length=255, verbose_name='M-Pesa API Secret')),
                ('mpesa_till_number', models.CharField(help_text='The Till or Paybill number to receive payments', max_length=20, verbose_name='M-Pesa Till/Paybill Number')),
                ('mpesa_shortcode_type', models.CharField(choices=[('till', 'Till'), ('paybill', 'Paybill')], default='till', max_length=20, verbose_name='Shortcode Type')),
                ('mpesa_passkey', models.CharField(help_text='Used for M-Pesa Online STK Push', max_length=255, verbose_name='M-Pesa Online LNM Passkey')),
                ('telegram_bot_token', models.CharField(help_text='Unique per business for security', max_length=255, unique=True, verbose_name='Telegram Bot Token')),
                ('webhook_secret', models.CharField(help_text='Used to verify webhook authenticity', max_length=255, unique=True, verbose_name='Webhook Secret')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Set to True after Daraja and Telegram webhooks are verified')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('checkout_request_id', models.CharField(help_text='Unique ID from Daraja STK push initiation', max_length=255, unique=True, verbose_name='Checkout Request ID')),
                ('request_id', models.CharField(blank=True, help_text='Unique identifier used in requests to Daraja', max_length=255, verbose_name='Request ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount (KSH)')),
                ('mpesa_receipt_number', models.CharField(blank=True, help_text='Receipt returned by M-Pesa on successful payment', max_length=50, verbose_name='M-Pesa Receipt Number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Payment Status')),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='STK push expires after 2 minutes (120 seconds)')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contrib.business')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentCallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('callback_data', models.JSONField(verbose_name='Raw Callback Data')),
                ('result_code', models.CharField(blank=True, max_length=20, verbose_name='Result Code')),
                ('result_description', models.TextField(blank=True, verbose_name='Result Description')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_callbacks', to='contrib.business')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='callbacks', to='contrib.payment')),
            ],
            options={
                'verbose_name': 'Payment Callback',
                'verbose_name_plural': 'Payment Callbacks',
            },
        ),
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=255, verbose_name='Channel Name')),
                ('telegram_channel_id', models.CharField(help_text='The numeric ID of the Telegram channel', max_length=50, verbose_name='Telegram Channel ID')),
                ('description', models.TextField(blank=True, verbose_name='Channel Description')),
                ('price_ksh', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subscription Price (KSH)')),
                ('duration_days', models.PositiveIntegerField(default=30, help_text='How many days until subscription expires', verbose_name='Subscription Duration (Days)')),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_channels', to='contrib.business')),
            ],
            options={
                'verbose_name': 'Telegram Channel',
                'verbose_name_plural': 'Telegram Channels',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When the subscription expires')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20, verbose_name='Subscription Status')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='contrib.business')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription', to='contrib.payment')),
                ('telegram_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='contrib.telegramchannel')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='telegram_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contrib.telegramchannel'),
        ),
        migrations.CreateModel(
            name='TelegramChannelInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('invite_link', models.URLField(blank=True, verbose_name='Invite Link')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('failed', 'Failed'), ('revoked', 'Revoked')], default='pending', max_length=20, verbose_name='Invite Status')),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_invites', to='contrib.business')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='contrib.subscription')),
                ('telegram_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='contrib.telegramchannel')),
            ],
            options={
                'verbose_name': 'Telegram Channel Invite',
                'verbose_name_plural': 'Telegram Channel Invites',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('telegram_user_id', models.CharField(help_text='The numeric ID of the Telegram user', max_length=50, verbose_name='Telegram User ID')),
                ('telegram_username', models.CharField(blank=True, help_text='@username if available', max_length=255, verbose_name='Telegram Username')),
                ('phone_number', models.CharField(blank=True, help_text='Phone number used for M-Pesa payments (e.g., 2547XXXXXXX)', max_length=20, verbose_name='Phone Number')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_users', to='contrib.business')),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram Users',
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='telegram_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='contrib.telegramuser'),
        ),
        migrations.AddField(
            model_name='payment',
            name='telegram_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contrib.telegramuser'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['owner', 'is_active'], name='contrib_bus_owner_i_1bb1f9_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['slug'], name='contrib_bus_slug_dba8df_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcallback',
            index=models.Index(fields=['business', 'created'], name='contrib_pay_busines_df854f_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramchannel',
            index=models.Index(fields=['business', 'is_active'], name='contrib_tel_busines_3216cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='telegramchannel',
            unique_together={('business', 'telegram_channel_id')},
        ),
        migrations.AddIndex(
            model_name='telegramchannelinvite',
            index=models.Index(fields=['subscription', 'status'], name='contrib_tel_subscri_e5ef25_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramchannelinvite',
            index=models.Index(fields=['business', 'status'], name='contrib_tel_busines_44bc8b_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramuser',
            index=models.Index(fields=['business', 'telegram_user_id'], name='contrib_tel_busines_dbee51_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='telegramuser',
            unique_together={('business', 'telegram_user_id')},
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['business', 'status'], name='contrib_sub_busines_638e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['telegram_user', 'status'], name='contrib_sub_telegra_34d8e2_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'expires_at'], name='contrib_sub_status_0401b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('telegram_user', 'telegram_channel')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['business', 'status'], name='contrib_pay_busines_b6f741_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['telegram_user', 'status'], name='contrib_pay_telegra_6707e6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['checkout_request_id'], name='contrib_pay_checkou_5e8ec7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'expires_at'], name='contrib_pay_status_8dbd19_idx'),
        ),
    ]
