# Generated by Django 6.0.3 on 2026-03-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
